---

- name: Install dependencies for postgres connection
  apt: name={{ item }} update_cache=yes force=yes state=installed
  with_items:
    - postgresql-client-common
    - postgresql-client
    - python-psycopg2

- name: Set fact with flattened list of databases
  set_fact: 
    flat_dbs: "{{ flat_dbs|default([]) + [ item.target ] + ( [ item.replacement ]  | default([]) ) }}"
  with_items: "{{ databases }}"

- name: Drop target databases if specified
  include: drop.yml
  when: drop_db is defined and drop_db

- name: Make sure the specified databases are present
  postgresql_db:
    name: "{{ item }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
    state: present
    owner: "{{ db_owner }}"
    login_host: "{{ db_host }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
  with_items: "{{ flat_dbs }}"

- include_tasks: swap.yml
  when: swap_db is defined and swap_db

- name: Ensure users have proper permissions on all dbs
  include_tasks: grant.yml