---

- name: Rename old target
  shell: "{{ psql_cnxn }} -c 'ALTER DATABASE {{ item.current }} RENAME TO {{ item.new }};'"
  with_items:
    - current: "{{ target }}"
      new: "{{ new_target_name }}" 
  tags: db-swap

- name: Create target db from replacement db
  shell: "{{ psql_cnxn }} -c 'CREATE DATABASE {{ target }} WITH TEMPLATE {{ replacement }} WITH OWNER {{ db_owner }};'"
  tags: db-swap