---

- name: Rename old target and replace with current replacement
  shell: "{{ psql_cnxn }} -c 'ALTER DATABASE {{ item.current }} RENAME TO {{ item.new }};'"
  with_items:
    - current: "{{ target }}"
      new: "{{ new_target_name }}" 
    - current: "{{ replacement }}"
      new: "{{ target }}"
  tags: db-swap

- name: Recreate replacement db
  shell: "{{ psql_cnxn }} -c 'CREATE DATABASE {{ replacement }} WITH OWNER {{ db_owner }};'"
  tags: db-swap