---

- name: Rename old target
  shell: "{{ psql_cnxn }} -c 'ALTER DATABASE {{ item.current }} RENAME TO {{ item.new }};'"
  with_items:
    - current: "{{ target }}"
      new: "{{ new_target_name }}" 
    - current: "{{ replacement }}"
      new: "{{ target }}"
  tags: db-swap

- name: Re-create replacement db (optionally using target as template)
  shell: "{{ psql_cnxn }} -c 'CREATE DATABASE {{ replacement }}{{ keep_replacement | ternary(' WITH TEMPLATE ' ~ target, '')  }} OWNER {{ db_owner }};'"
  tags: db-swap