---

- set_fact: 
    dbs_to_kill: "{{ flat_dbs }}"

- name: Kill connections to all dbs
  include_tasks: kill.yml

- name: Loop over databases and swap names
  include_tasks: single_swap.yml 
  vars: 
    target: "{{ db.target }}"
    replacement: "{{ db.replacement }}"
    new_target_name: "{{ db.new_target_name | default(new_target_prefix ~ db.target ~ new_target_suffix) }}"
  with_items: "{{ databases }}"
  loop_control:
    loop_var: db